fruit_tuple=(
    "apple", 
    "apricot",
    "avocado",
    "banana", 
    "blackberry",
    "blackberries",
    "blueberry", 
    "blueberries",
    "clementine",
    "cherry", 
    "cherries", 
    "coconut",
    "crabapple",
    "cranberry",
    "cranberries",
    "grapefruit",
    "grapes", 
    "keyLime",
    "kiwi", 
    "lemon",
    "lime", 
    "mandarin", 
    "mango", 
    "melon", 
    "mixed fruit",
    "mulberry", 
    "mulberries", 
    "nectarine",
    "olive", 
    "orange",
    "papaya", 
    "passionfruit", 
    "peach", 
    "pear", 
    "pineapple", 
    "plum",
    "pomegranate",
    "raspberry",
    "raspberries",
    "strawberry",
    "strawberries",
    "tangerine",
    "tomato",
    "watermelon",
    "other_fruit",
    )


fruit_choices=(
    ("apple", "Apple"),
    ("apricot", "Apricot"),
    ("avocado", "Avocado"),
    ("banana", "Banana"),
    ("blackberry", "Blackberry"),
    ("blueberry", "Blueberry"),
    ("cherry", "Cherry"),
    ("coconut", "Coconut"),
    ("crabapple", "Crabapple"),
    ("cranberry", "Cranberry"),
    ("clementine","Clementine"),
    ("grapefruit", "Grapefruit"),
    ("grape", "Grapes"),
    ("keylime", "Key Lime"),
    ("kiwi", "Kiwi"),
    ("lemon", "Lemon"),
    ("lime", "Lime"),
    ("mandarin", "Mandarin"),
    ("mango", "Mango"),
    ("melon", "Melon"),
    ("mixed fruit", "Mixed Fruit"),
    ("mulberry", "Mulberry"),
    ("nectarine", "Nectarines"),
    ("orange", "Orange"),
    ("papaya", "Papaya"),
    ("passionfruit", "PassionFruit"),
    ("peach", "Peach"),
    ("pear", "Pear"),
    ("pineapple", "Pineapple"),
    ("plum", "Plum"),
    ("pomegranate", "Pomegranate"),
    ("raspberry", "Raspberry"),
    ("strawberry", "Strawberry"),
    ("tangerine", "Tangerine"),
    ("tomato", "Tomato"),
    ("watermelon", "Watermelon"),
    )


veg_tuple=(
    "asparagus",
    "beets",
    "bell pepper", 
    "broccoli", 
    "brussel sprouts", 
    "cabbage", 
    "carrot", 
    "cauliflower", 
    "celery", 
    "collard greens", 
    "corn", 
    "cucumber", 
    "eggplant", 
    "garlic", 
    "green bean", 
    "green peas", 
    "kale",
    "mushroom",
    "mixed vegetables",
    "okra",
    "olive",
    "onion", 
    "parsnip",
    "potato",
    "pumpkin", 
    "lettuce romaine",
    "lettuce green leafy",
    "lettuce iceburg",
    "lettuce",
    "spinach",
    "squash",
    "sweet potato",
    "turnip greens",
    "watercress",
    "yam",
    "zucchini",
    "other_veg",
)

veg_choices=(
    ("asparagus", "Asparagus"),
    ("beets", "Beets"),
    ("bell pepper", "BellPeppers"),
    ("broccoli", "Broccoli"),
    ("brussel sprouts", "Brussels Sprouts"),
    ("cabbage", "Cabbage"),
    ("carrot", "Carrots"),
    ("cauliflower", "Cauliflower"),
    ("celery", "Celery"),
    ("collard greens", "Collard greens"),
    ("corn", "Corn"),
    ("cucumber", "Cucumbers"),
    ("eggplant", "Eggplant"),
    ("garlic", "Garlic"),
    ("green bean", "Green beans"),
    ("green pea", "Green peas"),
    ("kale", "Kale"),
    ("mushroom", "Mushrooms"),
    ("mixed vegetables", "Mixed Vegetables"),
    ("okra", "Okra"),
    ("olive","Olives" ),
    ("onion", "Onions"),
    ("parsnip","Parsnips"),
    ("potato","Potatoes"),
    ("pumpkin", "Pumpkin"),    
    ("lettuce romanine", "Lettuce Romaine"),
    ("lettuce iceburg", "Lettuce Iceburg"),
    ("lettuce green leafy", "Lettuce Green Leafy"),
    ("spinach", "Spinach"),
    ("squash", "Squash"),
    ("sweet potato","Sweet potatoes" ),
    ("turnip greens", "Turnip greens"),
    ("watercress","Watercress" ),
    ("yam", "Yams"),
    ("zucchini", "Zucchini"),
)