fruit_tuple=(
    "apple", 
    "apricot",
    "avocado",
    "banana", 
    "blackberry",
    "blueberry", 
    "cherry", 
    "coconut",
    "crabapple",
    "cranberry",
    "grapefruit",
    "grapes", 
    "keyLime",
    "kiwi", 
    "lemon",
    "lime", 
    "mandarin", 
    "mango", 
    "melon", 
    "mulberry", 
    "nectarines",
    "olive", 
    "orange",
    "papaya", 
    "passionfruit", 
    "peach", 
    "pear", 
    "pineapple", 
    "plum",
    "pomegranate",
    "paspberry",
    "strawberry",
    "tangerine",
    "tomato",
    "watermelon",
    "other_fruit",
    )


fruit_choices=(
    ("apple", "Apple"),
    ("apricot", "Apricot"),
    ("avocado", "Avocado"),
    ("banana", "Banana"),
    ("blackberry", "Blackberry"),
    ("blueberry", "Blueberry"),
    ("cherry", "Cherry"),
    ("coconut", "Coconut"),
    ("crabapple", "Crabapple"),
    ("cranberry", "Cranberry"),
    ("grapefruit", "Grapefruit"),
    ("grapes", "Grapes"),
    ("keyLime", "KeyLime"),
    ("kiwi", "Kiwi"),
    ("lemon", "Lemon"),
    ("lime", "Lime"),
    ("mandarin", "Mandarin"),
    ("mango", "Mango"),
    ("melon", "Melon"),
    ("mulberry", "Mulberry"),
    ("nectarines", "Nectarines"),
    ("olive", "Olive"),
    ("orange", "Orange"),
    ("papaya", "Papaya"),
    ("passionfruit", "PassionFruit"),
    ("peach", "Peach"),
    ("pear", "Pear"),
    ("pineapple", "Pineapple"),
    ("plum", "Plum"),
    ("pomegranate", "Pomegranate"),
    ("paspberry", "Raspberry"),
    ("strawberry", "Strawberry"),
    ("tangerine", "Tangerine"),
    ("tomato", "Tomato"),
    ("watermelon", "Watermelon"),
    ("other_fruit", "Other Fruit"),
    )


veg_tuple=(
    "asparagus",
    "beets",
    "bell pepper", 
    "broccoli", 
    "brussel sprouts", 
    "cabbage", 
    "carrots", 
    "cauliflower", 
    "celery", 
    "collard greens", 
    "corn", 
    "cucumbers", 
    "eggplant", 
    "garlic", 
    "green beans", 
    "green peas", 
    "kale",
    "mushrooms",
    "okra",
    "olives",
    "onions", 
    "parsnips",
    "potatoes",
    "pumpkin", 
    "romaine lettuce",
    "spinach",
    "squash",
    "sweet potatoes",
    "turnip greens",
    "watercress",
    "yams",
    "zucchini",
    "other_veg",
)

veg_choices=(
    ("asparagus", "Asparagus"),
    ("beets", "Beets"),
    ("bell pepper", "BellPeppers"),
    ("broccoli", "Broccoli"),
    ("brussel sprouts", "Brussels Sprouts"),
    ("cabbage", "Cabbage"),
    ("carrots", "Carrots"),
    ("cauliflower", "Cauliflower"),
    ("celery", "Celery"),
    ("collard greens", "Collard greens"),
    ("corn", "Corn"),
    ("cucumbers", "Cucumbers"),
    ("eggplant", "Eggplant"),
    ("garlic", "Garlic"),
    ("green beans", "Green beans"),
    ("green peas", "Green peas"),
    ("kale", "Kale"),
    ("mushrooms", "Mushrooms"),
    ("okra", "Okra"),
    ("olives","Olives" ),
    ("onions", "Onions"),
    ("parsnips","Parsnips"),
    ("potatoes","Potatoes"),
    ("pumpkin", "Pumpkin"),
    ("romaine lettuce", "Romaine lettuce"),
    ("spinach", "Spinach"),
    ("squash", "Squash"),
    ("sweet potatoes","Sweet potatoes" ),
    ("turnip greens", "Turnip greens"),
    ("watercress","Watercress" ),
    ("yams", "Yams"),
    ("zucchini", "Zucchini"),
    ("other_veg", "Other Veg"),
)