from django.db import models

# Create your models here.
fruit_list=(
    ("Apple", "Apple"),
    ("Apricot", "Apricot"),
    ("Avocado", "Avocado"),
    ("Banana", "Banana"),
    ("Blackberry", "Blackberry"),
    ("Blueberry", "Blueberry"),
    ("Cherry", "Cherry"),
    ("Coconut", "Coconut"),
    ("Crabapple", "Crabapple"),
    ("Cranberry", "Cranberry"),
    ("Grapefruit", "Grapefruit"),
    ("Grapes", "Grapes"),
    ("KeyLime", "KeyLime"),
    ("Kiwi", "Kiwi"),
    ("Lemon", "Lemon"),
    ("Lime", "Lime"),
    ("Mandarin", "Mandarin"),
    ("Mango", "Mango"),
    ("Melon", "Melon"),
    ("Mulberry", "Mulberry"),
    ("Nectarines", "Nectarines"),
    ("Olive", "Olive"),
    ("Orange", "Orange"),
    ("Papaya", "Papaya"),
    ("PassionFruit", "PassionFruit"),
    ("Peach", "Peach"),
    ("Pear", "Pear"),
    ("Pineapple", "Pineapple"),
    ("Plum", "Plum"),
    ("Pomegranate", "Pomegranate"),
    ("Raspberry", "Raspberry"),
    ("Strawberry", "Strawberry"),
    ("Tangerine", "Tangerine"),
    ("Tomato", "Tomato"),
    ("Watermelon", "Watermelon"),
    )

veg_list=(
    ("Asparagus", "Asparagus"),
    ("Beets", "Beets"),
    ("BellPeppers", "BellPeppers"),
    ("Broccoli", "Broccoli"),
    ("Brussels Sprouts", "Brussels Sprouts"),
    ("Cabbage", "Cabbage"),
    ("Carrots", "Carrots"),
    ("Cauliflower", "Cauliflower"),
    ("Celery", "Celery"),
    ("Collard greens", "Collard greens"),
    ("Corn, yellow", "Corn, yellow"),
    ("Cucumbers", "Cucumbers"),
    ("Eggplant", "Eggplant"),
    ("Garlic", "Garlic"),
    ("Green beans", "Green beans"),
    ("Green peas", "Green peas"),
    ("Kale", "Kale"),
    ("Mushrooms", "Mushrooms"),
    ("Okra", "Okra"),
    ("Olives","Olives" ),
    ("Onions", "Onions"),
    ("Parsnips","Parsnips"),
    ("Potatoes","Potatoes"),
    ("Pumpkin", "Pumpkin"),
    ("Romaine lettuce", "Romaine lettuce"),
    ("Spinach", "Spinach"),
    ("Squash", "Squash"),
    ("Sweet potatoes","Sweet potatoes" ),
    ("Turnip greens", "Turnip greens"),
    ("Watercress","Watercress" ),
    ("Yams", "Yams"),
    ("Zucchini", "Zucchini"),
)

